# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flamingo < Formula
  desc "Flamingo CLI"
  homepage "https://flux-subsystem-argo.github.io/website/"
  version "0.10.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flux-subsystem-argo/flamingo/releases/download/v0.10.2/flamingo_0.10.2_darwin_amd64.tar.gz"
      sha256 "c9995a346360fb273f0b969ea10134e1464f1729a28b5d3fba0b57b7f12f5866"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flux-subsystem-argo/flamingo/releases/download/v0.10.2/flamingo_0.10.2_darwin_arm64.tar.gz"
      sha256 "c62fdb51aeb0482f2b0493d2a151fb8f13315bfddb288928fa719dc77042c555"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flux-subsystem-argo/flamingo/releases/download/v0.10.2/flamingo_0.10.2_linux_arm64.tar.gz"
      sha256 "76d721e0c81d9f0a59d2ae25e8546b43b4bac385011600395b3e70ee7ac61ead"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flux-subsystem-argo/flamingo/releases/download/v0.10.2/flamingo_0.10.2_linux_amd64.tar.gz"
      sha256 "611927ecc32561bd0bb8bbcac804db56b0d3bb101ee1cdeff1f1f3fe9f111566"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
  end

  test do
    system "#{bin}/flamingo --version"
  end
end
