# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flamingo < Formula
  desc "Flamingo CLI"
  homepage "https://flux-subsystem-argo.github.io/website/"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flux-subsystem-argo/flamingo/releases/download/v0.6.0/flamingo_0.6.0_darwin_amd64.tar.gz"
      sha256 "a296005cec1c6c893119d852847e9b4ab1ab0ba4435a27adeb8a2a53e1c3e20c"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flux-subsystem-argo/flamingo/releases/download/v0.6.0/flamingo_0.6.0_darwin_arm64.tar.gz"
      sha256 "44a5a139db6686a63ebaa8e56790e1e208a6f4181aa5c4696d322a93ac0c255a"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flux-subsystem-argo/flamingo/releases/download/v0.6.0/flamingo_0.6.0_linux_arm64.tar.gz"
      sha256 "78ab26b7d8786c83bd473228490c76592db417cca7b1adef1b2aec22572d00ff"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flux-subsystem-argo/flamingo/releases/download/v0.6.0/flamingo_0.6.0_linux_amd64.tar.gz"
      sha256 "b2bc8969afcd92390e0cd658119af75fe8c4b4a1263e424b78c4024f6244b839"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
  end

  test do
    system "#{bin}/flamingo --version"
  end
end
