# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flamingo < Formula
  desc "Flamingo CLI"
  homepage "https://flux-subsystem-argo.github.io/website/"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flux-subsystem-argo/cli/releases/download/v0.0.1/flamingo_0.0.1_darwin_amd64.tar.gz"
      sha256 "686e44279572d38fde5e71ed11867562faf732431d2b63fb7226d5ba8088f3c7"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flux-subsystem-argo/cli/releases/download/v0.0.1/flamingo_0.0.1_darwin_arm64.tar.gz"
      sha256 "cd13d8226e9df71e128d7cc0d9562925c73e84e68c8d29c2f1ade51e4ee6f3a3"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flux-subsystem-argo/cli/releases/download/v0.0.1/flamingo_0.0.1_linux_arm64.tar.gz"
      sha256 "831c65ca69ce7a3d926e97d8356fb637a8d94a5ccfcf2264acfa828b50f3e642"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flux-subsystem-argo/cli/releases/download/v0.0.1/flamingo_0.0.1_linux_amd64.tar.gz"
      sha256 "29f51cac9a60213dcc413dce8319e8c8f7fb1727097c8aaef37f5c29d61e1a44"

      def install
        bin.install "flamingo"

        generate_completions_from_executable(bin/"flamingo", "completion")
      end
    end
  end

  test do
    system "#{bin}/flamingo --version"
  end
end
